apiVersion: 1
datasources:
  - name: JobForge Runs
    uid: jobforge-run-prometheus
    type: prometheus
    access: proxy
    url: http://run-prometheus:9090
    isDefault: true
    editable: false
  - name: JobForge Run traces
    uid: jobforge-run-jaeger
    type: jaeger
    access: proxy
    url: http://run-jaeger:16686
    editable: false
