package integration

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"

	"github.com/xjfyrh/jobforge/internal/domain"
	"github.com/xjfyrh/jobforge/internal/observability"
	"github.com/xjfyrh/jobforge/internal/store"
)

// TestTraceAT12Propagation verifies AT-12: Trace ID propagation.
//
// AT-12 Requirements:
//   - Submit a task with X-Trace-ID
//   - Verify trace_id is stored in job table
//   - Verify trace_id is returned in claim
//   - trace_id propagates from API → job → Worker
//
// Note: Full OTel span visualization is W6 scope. W5 verifies trace_id
// propagation at the data and log level.
func TestTraceAT12Propagation(t *testing.T) {
	js := setupStore(t)
	ctx := context.Background()

	// 1. Create a job with explicit trace_id (simulating X-Trace-ID header).
	traceID := "trace-" + uuid.New().String()
	jobID := uuid.New().String()
	pastRunAt := time.Now().Add(-1 * time.Second)

	job, err := domain.NewJob(jobID, domain.NewJobParams{
		TenantID: "test-tenant",
		Queue:    "trace-test",
		Type:     "demo.echo",
		Payload:  []byte(`{"test":true}`),
		RunAt:    &pastRunAt,
		TraceID:  &traceID,
	}, time.Now())
	if err != nil {
		t.Fatalf("create job: %v", err)
	}

	_, err = js.Enqueue(ctx, job)
	if err != nil {
		t.Fatalf("enqueue: %v", err)
	}

	// 2. Verify trace_id is stored in job table.
	got, err := js.GetByID(ctx, "test-tenant", jobID)
	if err != nil {
		t.Fatalf("get job: %v", err)
	}

	if got.TraceID == nil {
		t.Fatal("expected trace_id to be set in job table")
	}
	if *got.TraceID != traceID {
		t.Errorf("expected trace_id=%s, got %s", traceID, *got.TraceID)
	}
	t.Logf("Job stored with trace_id=%s", *got.TraceID)

	// 3. Claim the job and verify trace_id is returned.
	claimed, err := js.Claim(ctx, store.ClaimParams{
		Queue:    "trace-test",
		WorkerID: "trace-worker",
		MaxJobs:  1,
		LeaseTTL: 30 * time.Second,
	})
	if err != nil {
		t.Fatalf("claim: %v", err)
	}
	if len(claimed) == 0 {
		t.Fatal("expected at least 1 claimed job")
	}

	claimedJob := claimed[0]
	if claimedJob.TraceID == nil {
		t.Fatal("expected trace_id in claimed job")
	}
	if *claimedJob.TraceID != traceID {
		t.Errorf("claimed job trace_id mismatch: expected %s, got %s", traceID, *claimedJob.TraceID)
	}
	t.Logf("Claimed job has trace_id=%s", *claimedJob.TraceID)

	// 4. Verify trace_id consistency through the lifecycle.
	// In a real system, the Worker would log with this trace_id,
	// allowing log correlation across API → Gateway → Worker.
	t.Log("AT-12 PASSED: trace_id propagates from API → job table → claim")
}

// TestTraceIDAutoGenerated verifies that when no X-Trace-ID is provided,
// a trace_id is auto-generated.
func TestTraceIDAutoGenerated(t *testing.T) {
	js := setupStore(t)
	ctx := context.Background()

	// Create job without explicit trace_id.
	jobID := uuid.New().String()
	pastRunAt := time.Now().Add(-1 * time.Second)

	job, err := domain.NewJob(jobID, domain.NewJobParams{
		TenantID: "test-tenant",
		Queue:    "trace-auto",
		Type:     "demo.echo",
		Payload:  []byte(`{}`),
		RunAt:    &pastRunAt,
		// TraceID not set - should be nil or auto-generated by API layer
	}, time.Now())
	if err != nil {
		t.Fatalf("create job: %v", err)
	}

	_, err = js.Enqueue(ctx, job)
	if err != nil {
		t.Fatalf("enqueue: %v", err)
	}

	// At the store level, trace_id may be nil if not set.
	// The API layer is responsible for generating trace_id.
	got, err := js.GetByID(ctx, "test-tenant", jobID)
	if err != nil {
		t.Fatalf("get job: %v", err)
	}

	// Store-level: trace_id can be nil (API layer generates it).
	t.Logf("Job trace_id at store level: %v", got.TraceID)
}

// TestTraceContextEndToEnd verifies FR-503 / AT-12 (full version): the W3C
// TraceContext captured at submission survives the database round trip and
// allows the Worker to start worker.execute as a child of the submit span.
func TestTraceContextEndToEnd(t *testing.T) {
	// In-memory span recorder with the W3C TraceContext propagator.
	recorder := tracetest.NewSpanRecorder()
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSpanProcessor(recorder),
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.TraceContext{})
	defer func() { _ = tp.Shutdown(context.Background()) }()

	js := setupStore(t)
	ctx := context.Background()

	// 1. API submit span; serialize its context to a traceparent value.
	tracer := tp.Tracer("jobforge.api")
	submitCtx, submitSpan := tracer.Start(ctx, "http.submit_job")
	tpVal := observability.InjectTraceParent(submitCtx)
	if tpVal == "" {
		t.Fatal("expected non-empty traceparent from active submit span")
	}

	// 2. Enqueue the job with the serialized trace context.
	jobID := uuid.New().String()
	pastRunAt := time.Now().Add(-1 * time.Second)
	traceID := "tctx-" + uuid.New().String()
	job, err := domain.NewJob(jobID, domain.NewJobParams{
		TenantID:     "tctx-tenant",
		Queue:        "tctx-queue",
		Type:         "demo.echo",
		Payload:      []byte(`{}`),
		RunAt:        &pastRunAt,
		TraceID:      &traceID,
		TraceContext: &tpVal,
	}, time.Now())
	if err != nil {
		t.Fatalf("create job: %v", err)
	}
	if _, err := js.Enqueue(submitCtx, job); err != nil {
		t.Fatalf("enqueue: %v", err)
	}
	submitSpan.End()

	// 3. trace_context survives the GetByID round trip.
	got, err := js.GetByID(ctx, "tctx-tenant", jobID)
	if err != nil {
		t.Fatalf("get job: %v", err)
	}
	if got.TraceContext == nil || *got.TraceContext != tpVal {
		t.Fatalf("trace_context not persisted: got %v, want %q", got.TraceContext, tpVal)
	}

	// 4. Claim returns the trace context to the Worker.
	claimed, err := js.Claim(ctx, store.ClaimParams{
		Queue:    "tctx-queue",
		WorkerID: "tctx-worker",
		MaxJobs:  1,
		LeaseTTL: 30 * time.Second,
	})
	if err != nil || len(claimed) == 0 {
		t.Fatalf("claim: %v (claimed %d)", err, len(claimed))
	}
	if claimed[0].TraceContext == nil || *claimed[0].TraceContext != tpVal {
		t.Fatalf("claimed job lost trace_context: %v", claimed[0].TraceContext)
	}

	// 5. Worker restores the remote span context and starts a child span.
	workerCtx := observability.ContextWithTraceParent(context.Background(), *claimed[0].TraceContext)
	_, execSpan := tp.Tracer("jobforge.worker").Start(workerCtx, "worker.execute")
	execSpan.End()
	_ = tp.Shutdown(context.Background())

	// 6. Verify parent-child linkage across the process boundary.
	var submitSpanID, workerTraceID, workerParentID string
	for _, s := range recorder.Ended() {
		switch s.Name() {
		case "http.submit_job":
			submitSpanID = s.SpanContext().SpanID().String()
		case "worker.execute":
			workerTraceID = s.SpanContext().TraceID().String()
			workerParentID = s.Parent().SpanID().String()
		}
	}
	if submitSpanID == "" || workerTraceID == "" {
		t.Fatalf("missing spans in recorder: %v", recorder.Ended())
	}
	if workerTraceID != submitSpan.SpanContext().TraceID().String() {
		t.Errorf("worker span trace %s != submit span trace %s",
			workerTraceID, submitSpan.SpanContext().TraceID().String())
	}
	if workerParentID != submitSpanID {
		t.Errorf("worker span parent %s != submit span id %s", workerParentID, submitSpanID)
	}
	t.Log("FR-503 PASSED: submit -> DB -> claim -> worker span share one trace with parent linkage")
}

// TestTraceContextInvalidIgnored verifies that empty or malformed traceparent
// values never panic and leave the context unchanged.
func TestTraceContextInvalidIgnored(t *testing.T) {
	ctx := context.Background()
	if got := observability.ContextWithTraceParent(ctx, ""); got != ctx {
		t.Error("empty traceparent must return the original context")
	}
	if got := observability.ContextWithTraceParent(ctx, "not-a-traceparent"); got != ctx {
		t.Error("invalid traceparent must return the original context")
	}
}
