// JobForge Worker API v1
//
// This proto defines the gRPC contract between the Go Worker Runtime and the
// Worker Gateway. All RPCs are unary (ADR-0001). The Worker initiates all
// calls; the Gateway never pushes to the Worker outside a Poll response.
//
// Package version: jobforge.worker.v1
// Compatibility policy: backward-compatible additions only. Removed or
// renumbered fields must be reserved. See docs/code-standards.md section 6.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobforge/worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlSignal instructs the Worker on what to do next.
type ControlSignal int32

const (
	// Continue execution normally. The zero value deliberately means continue
	// so that an absent signal never interrupts a running job.
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	ControlSignal_CONTROL_SIGNAL_CONTINUE ControlSignal = 0
	// Cancel execution as soon as possible. The job has a pending cancel
	// request. Worker should stop work and call Fail or simply stop heartbeating.
	ControlSignal_CONTROL_SIGNAL_CANCEL ControlSignal = 1
)

// Enum value maps for ControlSignal.
var (
	ControlSignal_name = map[int32]string{
		0: "CONTROL_SIGNAL_CONTINUE",
		1: "CONTROL_SIGNAL_CANCEL",
	}
	ControlSignal_value = map[string]int32{
		"CONTROL_SIGNAL_CONTINUE": 0,
		"CONTROL_SIGNAL_CANCEL":   1,
	}
)

func (x ControlSignal) Enum() *ControlSignal {
	p := new(ControlSignal)
	*p = x
	return p
}

func (x ControlSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_jobforge_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (ControlSignal) Type() protoreflect.EnumType {
	return &file_jobforge_worker_v1_worker_proto_enumTypes[0]
}

func (x ControlSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlSignal.Descriptor instead.
func (ControlSignal) EnumDescriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

// DomainErrorDetail carries the stable JobForge error classification attached
// to every unsuccessful Worker RPC. Clients should prefer this detail over
// inferring behavior from the transport status alone.
type DomainErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable machine-readable code from ADR-0002 (for example STALE_LEASE).
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Whether retrying this control-plane operation is safe after backoff.
	Retryable     bool `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainErrorDetail) Reset() {
	*x = DomainErrorDetail{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainErrorDetail) ProtoMessage() {}

func (x *DomainErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainErrorDetail.ProtoReflect.Descriptor instead.
func (*DomainErrorDetail) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *DomainErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DomainErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// RegisterRequest announces Worker identity and capabilities.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Worker instance identifier (UUID). Assigned by the Worker process.
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Human-readable instance label for observability (e.g. hostname-pid).
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Queue names this Worker polls from.
	Queues []string `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	// Task types this Worker can execute (e.g. "demo.echo", "pagewise.reindex").
	SupportedTypes []string `protobuf:"bytes,4,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	// Maximum concurrent jobs this Worker can handle.
	Capacity int32 `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Worker software version for observability and rolling upgrades.
	Version       string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *RegisterRequest) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *RegisterRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RegisterResponse confirms registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned session identifier for correlation in logs.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Suggested heartbeat interval. Worker should respect this.
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

// PollRequest asks the Gateway for available job leases.
type PollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Worker's registered identifier.
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Maximum number of jobs to claim in this batch.
	MaxJobs int32 `protobuf:"varint,2,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`
	// Current available capacity (capacity - inflight). Gateway uses this to
	// avoid over-assigning.
	AvailableCapacity int32 `protobuf:"varint,3,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	// Queue names to poll from. Must be a subset of registered queues.
	Queues []string `protobuf:"bytes,4,rep,name=queues,proto3" json:"queues,omitempty"`
	// Task types the Worker is willing to accept. Must be a subset of
	// registered types.
	Types         []string `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PollRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PollRequest) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *PollRequest) GetAvailableCapacity() int32 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

func (x *PollRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *PollRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

// PollResponse returns claimed job leases.
type PollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Claimed jobs. Empty if no work available before deadline.
	Jobs          []*ClaimedJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *PollResponse) GetJobs() []*ClaimedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// ClaimedJob represents a single job lease granted to the Worker.
type ClaimedJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job unique identifier.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Logical queue name.
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// Registered task type (e.g. "demo.echo").
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Task payload as JSON bytes. Max 256 KiB.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Current attempt number (1-based).
	Attempt int32 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Maximum allowed attempts for this job.
	MaxAttempts int32 `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Fencing token for this lease. Must be included in Heartbeat/Complete/Fail.
	FencingToken int64 `protobuf:"varint,7,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// Lease expiration time. Worker must complete or heartbeat before this.
	LeaseUntil *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	// Per-attempt execution timeout. Handler context deadline.
	Timeout *durationpb.Duration `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Trace identifier for distributed tracing correlation.
	TraceId string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Serialized W3C TraceContext (traceparent header value) captured at job
	// submission. Workers extract it to attach worker.execute spans to the
	// original submit trace (FR-503 / AT-12). Empty for legacy jobs.
	TraceContext  string `protobuf:"bytes,11,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimedJob) Reset() {
	*x = ClaimedJob{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedJob) ProtoMessage() {}

func (x *ClaimedJob) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimedJob.ProtoReflect.Descriptor instead.
func (*ClaimedJob) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimedJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ClaimedJob) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ClaimedJob) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClaimedJob) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClaimedJob) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ClaimedJob) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ClaimedJob) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ClaimedJob) GetLeaseUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseUntil
	}
	return nil
}

func (x *ClaimedJob) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ClaimedJob) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClaimedJob) GetTraceContext() string {
	if x != nil {
		return x.TraceContext
	}
	return ""
}

// HeartbeatRequest extends the lease and reports progress.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job being heartbeated.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Worker that owns the lease.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Fencing token from the Poll response.
	FencingToken int64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// Optional progress percentage (0-100) for observability.
	ProgressPercent int32 `protobuf:"varint,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *HeartbeatRequest) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

// HeartbeatResponse returns the control signal from the Gateway.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Control action the Worker must take.
	Signal ControlSignal `protobuf:"varint,1,opt,name=signal,proto3,enum=jobforge.worker.v1.ControlSignal" json:"signal,omitempty"`
	// New lease expiration after extension.
	LeaseUntil    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSignal() ControlSignal {
	if x != nil {
		return x.Signal
	}
	return ControlSignal_CONTROL_SIGNAL_CONTINUE
}

func (x *HeartbeatResponse) GetLeaseUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseUntil
	}
	return nil
}

// CompleteRequest reports successful job completion.
type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job identifier.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Worker that executed the job.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Fencing token proving lease ownership.
	FencingToken int64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// Optional reference to the result (e.g. storage URI). Not stored inline.
	ResultRef string `protobuf:"bytes,4,opt,name=result_ref,json=resultRef,proto3" json:"result_ref,omitempty"`
	// Actual execution duration for metrics.
	Duration      *durationpb.Duration `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteRequest) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *CompleteRequest) GetResultRef() string {
	if x != nil {
		return x.ResultRef
	}
	return ""
}

func (x *CompleteRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// CompleteResponse confirms completion.
type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final job state (should be "succeeded").
	State         string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// FailRequest reports job execution failure.
type FailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job identifier.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Worker that attempted the job.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Fencing token proving lease ownership.
	FencingToken int64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// Machine-readable error code (e.g. "TIMEOUT", "DEPENDENCY_UNAVAILABLE").
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Human-readable error message. Must not contain secrets or full payloads.
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Whether the error is transient and the job should be retried.
	// Non-retryable errors (bad input, unknown type) go directly to dead.
	Retryable bool `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Actual execution duration before failure.
	Duration      *durationpb.Duration `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *FailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailRequest) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *FailRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *FailRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FailRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *FailRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// FailResponse confirms failure processing.
type FailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resulting job state: "retry_wait" or "dead".
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// If retry_wait, the earliest time the job will become ready again.
	NextRetryAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobforge_worker_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_jobforge_worker_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *FailResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FailResponse) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

var File_jobforge_worker_v1_worker_proto protoreflect.FileDescriptor

const file_jobforge_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1fjobforge/worker/v1/worker.proto\x12\x12jobforge.worker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"E\n" +
	"\x11DomainErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\"\xc6\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06queues\x18\x03 \x03(\tR\x06queues\x12'\n" +
	"\x0fsupported_types\x18\x04 \x03(\tR\x0esupportedTypes\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"{\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12H\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"\xa2\x01\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x19\n" +
	"\bmax_jobs\x18\x02 \x01(\x05R\amaxJobs\x12-\n" +
	"\x12available_capacity\x18\x03 \x01(\x05R\x11availableCapacity\x12\x16\n" +
	"\x06queues\x18\x04 \x03(\tR\x06queues\x12\x14\n" +
	"\x05types\x18\x05 \x03(\tR\x05types\"B\n" +
	"\fPollResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.jobforge.worker.v1.ClaimedJobR\x04jobs\"\xfb\x02\n" +
	"\n" +
	"ClaimedJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12#\n" +
	"\rfencing_token\x18\a \x01(\x03R\ffencingToken\x12;\n" +
	"\vlease_until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"leaseUntil\x123\n" +
	"\atimeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12#\n" +
	"\rtrace_context\x18\v \x01(\tR\ftraceContext\"\x96\x01\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x03R\ffencingToken\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x05R\x0fprogressPercent\"\x8b\x01\n" +
	"\x11HeartbeatResponse\x129\n" +
	"\x06signal\x18\x01 \x01(\x0e2!.jobforge.worker.v1.ControlSignalR\x06signal\x12;\n" +
	"\vlease_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"leaseUntil\"\xc0\x01\n" +
	"\x0fCompleteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x03R\ffencingToken\x12\x1d\n" +
	"\n" +
	"result_ref\x18\x04 \x01(\tR\tresultRef\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\"(\n" +
	"\x10CompleteResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"\xff\x01\n" +
	"\vFailRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x03R\ffencingToken\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\"d\n" +
	"\fFailResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12>\n" +
	"\rnext_retry_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt*G\n" +
	"\rControlSignal\x12\x1b\n" +
	"\x17CONTROL_SIGNAL_CONTINUE\x10\x00\x12\x19\n" +
	"\x15CONTROL_SIGNAL_CANCEL\x10\x012\xad\x03\n" +
	"\rWorkerService\x12U\n" +
	"\bRegister\x12#.jobforge.worker.v1.RegisterRequest\x1a$.jobforge.worker.v1.RegisterResponse\x12I\n" +
	"\x04Poll\x12\x1f.jobforge.worker.v1.PollRequest\x1a .jobforge.worker.v1.PollResponse\x12X\n" +
	"\tHeartbeat\x12$.jobforge.worker.v1.HeartbeatRequest\x1a%.jobforge.worker.v1.HeartbeatResponse\x12U\n" +
	"\bComplete\x12#.jobforge.worker.v1.CompleteRequest\x1a$.jobforge.worker.v1.CompleteResponse\x12I\n" +
	"\x04Fail\x12\x1f.jobforge.worker.v1.FailRequest\x1a .jobforge.worker.v1.FailResponseB>Z<github.com/xjfyrh/jobforge/proto/jobforge/worker/v1;workerv1b\x06proto3"

var (
	file_jobforge_worker_v1_worker_proto_rawDescOnce sync.Once
	file_jobforge_worker_v1_worker_proto_rawDescData []byte
)

func file_jobforge_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_jobforge_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_jobforge_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobforge_worker_v1_worker_proto_rawDesc), len(file_jobforge_worker_v1_worker_proto_rawDesc)))
	})
	return file_jobforge_worker_v1_worker_proto_rawDescData
}

var file_jobforge_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobforge_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_jobforge_worker_v1_worker_proto_goTypes = []any{
	(ControlSignal)(0),            // 0: jobforge.worker.v1.ControlSignal
	(*DomainErrorDetail)(nil),     // 1: jobforge.worker.v1.DomainErrorDetail
	(*RegisterRequest)(nil),       // 2: jobforge.worker.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: jobforge.worker.v1.RegisterResponse
	(*PollRequest)(nil),           // 4: jobforge.worker.v1.PollRequest
	(*PollResponse)(nil),          // 5: jobforge.worker.v1.PollResponse
	(*ClaimedJob)(nil),            // 6: jobforge.worker.v1.ClaimedJob
	(*HeartbeatRequest)(nil),      // 7: jobforge.worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 8: jobforge.worker.v1.HeartbeatResponse
	(*CompleteRequest)(nil),       // 9: jobforge.worker.v1.CompleteRequest
	(*CompleteResponse)(nil),      // 10: jobforge.worker.v1.CompleteResponse
	(*FailRequest)(nil),           // 11: jobforge.worker.v1.FailRequest
	(*FailResponse)(nil),          // 12: jobforge.worker.v1.FailResponse
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_jobforge_worker_v1_worker_proto_depIdxs = []int32{
	13, // 0: jobforge.worker.v1.RegisterResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	6,  // 1: jobforge.worker.v1.PollResponse.jobs:type_name -> jobforge.worker.v1.ClaimedJob
	14, // 2: jobforge.worker.v1.ClaimedJob.lease_until:type_name -> google.protobuf.Timestamp
	13, // 3: jobforge.worker.v1.ClaimedJob.timeout:type_name -> google.protobuf.Duration
	0,  // 4: jobforge.worker.v1.HeartbeatResponse.signal:type_name -> jobforge.worker.v1.ControlSignal
	14, // 5: jobforge.worker.v1.HeartbeatResponse.lease_until:type_name -> google.protobuf.Timestamp
	13, // 6: jobforge.worker.v1.CompleteRequest.duration:type_name -> google.protobuf.Duration
	13, // 7: jobforge.worker.v1.FailRequest.duration:type_name -> google.protobuf.Duration
	14, // 8: jobforge.worker.v1.FailResponse.next_retry_at:type_name -> google.protobuf.Timestamp
	2,  // 9: jobforge.worker.v1.WorkerService.Register:input_type -> jobforge.worker.v1.RegisterRequest
	4,  // 10: jobforge.worker.v1.WorkerService.Poll:input_type -> jobforge.worker.v1.PollRequest
	7,  // 11: jobforge.worker.v1.WorkerService.Heartbeat:input_type -> jobforge.worker.v1.HeartbeatRequest
	9,  // 12: jobforge.worker.v1.WorkerService.Complete:input_type -> jobforge.worker.v1.CompleteRequest
	11, // 13: jobforge.worker.v1.WorkerService.Fail:input_type -> jobforge.worker.v1.FailRequest
	3,  // 14: jobforge.worker.v1.WorkerService.Register:output_type -> jobforge.worker.v1.RegisterResponse
	5,  // 15: jobforge.worker.v1.WorkerService.Poll:output_type -> jobforge.worker.v1.PollResponse
	8,  // 16: jobforge.worker.v1.WorkerService.Heartbeat:output_type -> jobforge.worker.v1.HeartbeatResponse
	10, // 17: jobforge.worker.v1.WorkerService.Complete:output_type -> jobforge.worker.v1.CompleteResponse
	12, // 18: jobforge.worker.v1.WorkerService.Fail:output_type -> jobforge.worker.v1.FailResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_jobforge_worker_v1_worker_proto_init() }
func file_jobforge_worker_v1_worker_proto_init() {
	if File_jobforge_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobforge_worker_v1_worker_proto_rawDesc), len(file_jobforge_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobforge_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_jobforge_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_jobforge_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_jobforge_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_jobforge_worker_v1_worker_proto = out.File
	file_jobforge_worker_v1_worker_proto_goTypes = nil
	file_jobforge_worker_v1_worker_proto_depIdxs = nil
}
