// Agent Run Worker protocol. PostgreSQL is the execution authority; all RPCs
// require a deadline and a separately authenticated internal Worker principal.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jobforge/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName           = "/jobforge.agent.v1.AgentService/Register"
	AgentService_Claim_FullMethodName              = "/jobforge.agent.v1.AgentService/Claim"
	AgentService_Heartbeat_FullMethodName          = "/jobforge.agent.v1.AgentService/Heartbeat"
	AgentService_GetCheckpoint_FullMethodName      = "/jobforge.agent.v1.AgentService/GetCheckpoint"
	AgentService_BeginTool_FullMethodName          = "/jobforge.agent.v1.AgentService/BeginTool"
	AgentService_ReserveCall_FullMethodName        = "/jobforge.agent.v1.AgentService/ReserveCall"
	AgentService_ObserveCall_FullMethodName        = "/jobforge.agent.v1.AgentService/ObserveCall"
	AgentService_SettleUsage_FullMethodName        = "/jobforge.agent.v1.AgentService/SettleUsage"
	AgentService_CommitStep_FullMethodName         = "/jobforge.agent.v1.AgentService/CommitStep"
	AgentService_FailAttempt_FullMethodName        = "/jobforge.agent.v1.AgentService/FailAttempt"
	AgentService_AcknowledgeStopped_FullMethodName = "/jobforge.agent.v1.AgentService/AcknowledgeStopped"
	AgentService_GetAcceptedCommit_FullMethodName  = "/jobforge.agent.v1.AgentService/GetAcceptedCommit"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService authorizes sequential Run execution, never arbitrary code or URLs.
// Errors carry google.rpc.ErrorInfo.reason with the ADR-0017 domain error code.
type AgentServiceClient interface {
	// Register binds a process startup identity to a configured Worker principal.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Claim atomically grants at most one Run; capacity is server configured.
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	// Heartbeat renews a live lease or requests local executor termination.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetCheckpoint reads committed results without checking remaining budget.
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// BeginTool counts one logical tool invocation; duplicates never authorize redo.
	BeginTool(ctx context.Context, in *BeginToolRequest, opts ...grpc.CallOption) (*BeginToolResponse, error)
	// ReserveCall grants one physical send only when newly_reserved is true.
	ReserveCall(ctx context.Context, in *ReserveCallRequest, opts ...grpc.CallOption) (*ReserveCallResponse, error)
	// ObserveCall records a current execution observation without advancing cursor.
	ObserveCall(ctx context.Context, in *ObserveCallRequest, opts ...grpc.CallOption) (*ObserveCallResponse, error)
	// SettleUsage settles only an existing call from its original principal/session.
	// It requires no live lease and cannot clear active_call or change Run state.
	SettleUsage(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*SettleUsageResponse, error)
	// CommitStep atomically stores a bounded result and computes the next cursor.
	CommitStep(ctx context.Context, in *CommitStepRequest, opts ...grpc.CallOption) (*CommitStepResponse, error)
	// FailAttempt closes a current attempt after its local executor has stopped.
	FailAttempt(ctx context.Context, in *FailAttemptRequest, opts ...grpc.CallOption) (*FailAttemptResponse, error)
	// AcknowledgeStopped closes stopping with its original attempt/session/token.
	AcknowledgeStopped(ctx context.Context, in *AcknowledgeStoppedRequest, opts ...grpc.CallOption) (*AcknowledgeStoppedResponse, error)
	// GetAcceptedCommit confirms lost ACKs read-only, including released leases.
	GetAcceptedCommit(ctx context.Context, in *GetAcceptedCommitRequest, opts ...grpc.CallOption) (*GetAcceptedCommitResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, AgentService_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, AgentService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) BeginTool(ctx context.Context, in *BeginToolRequest, opts ...grpc.CallOption) (*BeginToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginToolResponse)
	err := c.cc.Invoke(ctx, AgentService_BeginTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReserveCall(ctx context.Context, in *ReserveCallRequest, opts ...grpc.CallOption) (*ReserveCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveCallResponse)
	err := c.cc.Invoke(ctx, AgentService_ReserveCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ObserveCall(ctx context.Context, in *ObserveCallRequest, opts ...grpc.CallOption) (*ObserveCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveCallResponse)
	err := c.cc.Invoke(ctx, AgentService_ObserveCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SettleUsage(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*SettleUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleUsageResponse)
	err := c.cc.Invoke(ctx, AgentService_SettleUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CommitStep(ctx context.Context, in *CommitStepRequest, opts ...grpc.CallOption) (*CommitStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitStepResponse)
	err := c.cc.Invoke(ctx, AgentService_CommitStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FailAttempt(ctx context.Context, in *FailAttemptRequest, opts ...grpc.CallOption) (*FailAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailAttemptResponse)
	err := c.cc.Invoke(ctx, AgentService_FailAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AcknowledgeStopped(ctx context.Context, in *AcknowledgeStoppedRequest, opts ...grpc.CallOption) (*AcknowledgeStoppedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeStoppedResponse)
	err := c.cc.Invoke(ctx, AgentService_AcknowledgeStopped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAcceptedCommit(ctx context.Context, in *GetAcceptedCommitRequest, opts ...grpc.CallOption) (*GetAcceptedCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAcceptedCommitResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAcceptedCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService authorizes sequential Run execution, never arbitrary code or URLs.
// Errors carry google.rpc.ErrorInfo.reason with the ADR-0017 domain error code.
type AgentServiceServer interface {
	// Register binds a process startup identity to a configured Worker principal.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Claim atomically grants at most one Run; capacity is server configured.
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	// Heartbeat renews a live lease or requests local executor termination.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetCheckpoint reads committed results without checking remaining budget.
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// BeginTool counts one logical tool invocation; duplicates never authorize redo.
	BeginTool(context.Context, *BeginToolRequest) (*BeginToolResponse, error)
	// ReserveCall grants one physical send only when newly_reserved is true.
	ReserveCall(context.Context, *ReserveCallRequest) (*ReserveCallResponse, error)
	// ObserveCall records a current execution observation without advancing cursor.
	ObserveCall(context.Context, *ObserveCallRequest) (*ObserveCallResponse, error)
	// SettleUsage settles only an existing call from its original principal/session.
	// It requires no live lease and cannot clear active_call or change Run state.
	SettleUsage(context.Context, *SettleUsageRequest) (*SettleUsageResponse, error)
	// CommitStep atomically stores a bounded result and computes the next cursor.
	CommitStep(context.Context, *CommitStepRequest) (*CommitStepResponse, error)
	// FailAttempt closes a current attempt after its local executor has stopped.
	FailAttempt(context.Context, *FailAttemptRequest) (*FailAttemptResponse, error)
	// AcknowledgeStopped closes stopping with its original attempt/session/token.
	AcknowledgeStopped(context.Context, *AcknowledgeStoppedRequest) (*AcknowledgeStoppedResponse, error)
	// GetAcceptedCommit confirms lost ACKs read-only, including released leases.
	GetAcceptedCommit(context.Context, *GetAcceptedCommitRequest) (*GetAcceptedCommitResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedAgentServiceServer) BeginTool(context.Context, *BeginToolRequest) (*BeginToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTool not implemented")
}
func (UnimplementedAgentServiceServer) ReserveCall(context.Context, *ReserveCallRequest) (*ReserveCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveCall not implemented")
}
func (UnimplementedAgentServiceServer) ObserveCall(context.Context, *ObserveCallRequest) (*ObserveCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveCall not implemented")
}
func (UnimplementedAgentServiceServer) SettleUsage(context.Context, *SettleUsageRequest) (*SettleUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleUsage not implemented")
}
func (UnimplementedAgentServiceServer) CommitStep(context.Context, *CommitStepRequest) (*CommitStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitStep not implemented")
}
func (UnimplementedAgentServiceServer) FailAttempt(context.Context, *FailAttemptRequest) (*FailAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailAttempt not implemented")
}
func (UnimplementedAgentServiceServer) AcknowledgeStopped(context.Context, *AcknowledgeStoppedRequest) (*AcknowledgeStoppedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeStopped not implemented")
}
func (UnimplementedAgentServiceServer) GetAcceptedCommit(context.Context, *GetAcceptedCommitRequest) (*GetAcceptedCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAcceptedCommit not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_BeginTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).BeginTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_BeginTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).BeginTool(ctx, req.(*BeginToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReserveCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReserveCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReserveCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReserveCall(ctx, req.(*ReserveCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ObserveCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ObserveCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ObserveCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ObserveCall(ctx, req.(*ObserveCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SettleUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SettleUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SettleUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SettleUsage(ctx, req.(*SettleUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CommitStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CommitStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CommitStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CommitStep(ctx, req.(*CommitStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FailAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FailAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FailAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FailAttempt(ctx, req.(*FailAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AcknowledgeStopped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeStoppedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AcknowledgeStopped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AcknowledgeStopped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AcknowledgeStopped(ctx, req.(*AcknowledgeStoppedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAcceptedCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAcceptedCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAcceptedCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAcceptedCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAcceptedCommit(ctx, req.(*GetAcceptedCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobforge.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _AgentService_Claim_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _AgentService_GetCheckpoint_Handler,
		},
		{
			MethodName: "BeginTool",
			Handler:    _AgentService_BeginTool_Handler,
		},
		{
			MethodName: "ReserveCall",
			Handler:    _AgentService_ReserveCall_Handler,
		},
		{
			MethodName: "ObserveCall",
			Handler:    _AgentService_ObserveCall_Handler,
		},
		{
			MethodName: "SettleUsage",
			Handler:    _AgentService_SettleUsage_Handler,
		},
		{
			MethodName: "CommitStep",
			Handler:    _AgentService_CommitStep_Handler,
		},
		{
			MethodName: "FailAttempt",
			Handler:    _AgentService_FailAttempt_Handler,
		},
		{
			MethodName: "AcknowledgeStopped",
			Handler:    _AgentService_AcknowledgeStopped_Handler,
		},
		{
			MethodName: "GetAcceptedCommit",
			Handler:    _AgentService_GetAcceptedCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobforge/agent/v1/agent.proto",
}
